version: '3.8'

services:

  db:
    image: postgres:15.3-alpine
    volumes:
      - /var/lib/postgres/data
    environment:
      - POSTGRES_DB=share_id_DB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8 --locale=ru_RU.UTF-8"

  web:
    build: .
    ports:
      - "8080:8080"

    depends_on:
      - db

    environment:
      - DB_NAME=share_id_DB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
